language: elixir

elixir:
  - 1.5.3

otp_release:
  - 20.2

services:
  - postgresql

before_script:
  - MIX_ENV=test mix do event_store.create, event_store.init
  - epmd -daemon

sudo: required
dist: trusty

addons:
  postgresql: "9.6"
